# We use 2 different GOV.UK Notify services, one for development/integration
# purposes and another one for production. This is so we can test changes
# to the templates in a controlled environment, before these changes make their
# way to production (and real users can see them).
#
# As these are 2 separate services in GOV.UK Notify, the template IDs are also
# different, so we declare them in this file. We use the value of the variable
# ENV['GOVUK_NOTIFY_ENV'] if defined to know which group to load, otherwise
# we default to 'integration' group.
#
development:
  citizen_start_application: 74d7825f-91e4-4311-98a4-36cb517c8359 # this needs to be changed back and original email template amended
  feedback_notification: 4d391bf7-4e5b-4f49-b586-b6bb8ad06a30
  new_link_request: a577582b-3e60-44a4-885c-d4b12bf23958
  submission_confirmation: ce2d89ee-1c10-404b-91cc-52068933ba7b
  reminder_to_submit_an_application: 43de80f4-6a15-4be9-8a29-b3682cea3eee  # this needs to be changed back and original email template amended
  client_completed_means: d04e64ae-0a66-4577-83d6-6ce9f7fa27b4
  reminder_to_submit_financial_information_client: e8052551-2afa-4b11-b3e3-578248d9b582
  reminder_to_submit_financial_information_provider: ec4f423d-498a-4828-ab66-c2453cb42ed3
  new_link_to_client: 5708ec04-c789-4f7e-8a15-ad7dd3f4f336

production:
  citizen_start_application: 7e5fb1a7-4b78-4a95-917e-c0bcb78a5fcc
  feedback_notification: fd050a04-54d2-4736-bb6c-66431c7d9e41
  new_link_request: 3cc3be57-e072-4095-9caa-c0cd52193405
  submission_confirmation: 5472b10b-bc11-432a-a18d-9f20de5b2854
  reminder_to_submit_an_application: 96e58b6c-83e2-4ae8-be67-028803e98398
  client_completed_means: b343446d-b487-4f8b-9673-2aaf21ea10a1
  reminder_to_submit_financial_information_client: 2a07ae35-670a-4753-a7cf-58843068b659
  reminder_to_submit_financial_information_provider: 9843f667-8b11-41c0-9c11-622fffc686ec
  new_link_to_client: b59f52f3-ad0b-45ed-9b2a-a33686f4278a
